### ISSUE TITLE
Signing up fails

### ISSUE THREAD

**Issue by tituspijean** [tituspijean/flarum-ext-auth-ldap#6]
(see next message)

**Comment by popindavibe** [comment]
Hello,

I am stuck at login page, though on debug mode I can see that it was successful and I can see my user's email info.
However username shows `"username":null`
Is it part of the known bug?

**Comment by popindavibe** [comment]
Ok, for username it is just because as it is it requires a `displayName` associated to user.

That's ok. However no matter what I try I get an Oops error and back to login, though Debug shows all my values OK.

@tituspijean can you confirm it still works with version  0.1.0-beta.7 of Flarum?

**Comment by tituspijean** [comment]
I have just tested with version 0.1.0-beta.7 of Flarum, and latest @dev version of the extension. No problem beside the error "200 OK": I am actually logged in after refreshing the page.

Where did you see the `"username":null` ? It should not rely on `displayName`.

**Comment by popindavibe** [comment]
it was looking for displayName from:
```
$suggestions = [
                'username' => $user->getDisplayName(),
                'email' => $user->mail[0]
```
But that's ok, I replaced it by uid.

However, no matter what I try, I get an `Oops` from the login page and it stays there forever.
Activating debug and trying to pinpoint it (since authentication IS successful), I could follow up to main core file `vendor/flarum/core/src/Forum/AuthenticationResponseFactory.php` where the following gives no results:
```
$user = User::where($identification)->first();
```
Since my user does not exist in DB, I guess? 
Where is it that you tell Flarum to not look for the user in the DB at all?

**Comment by popindavibe** [comment]
my bad, it does go through! a refresh indeed...! We need to fix that :-)

**Comment by tituspijean** [comment]
Oh my bad! Yesterday I tested logging in with an already existing user in Flarum. Bug confirmed, I have the same issue with a similar extension I wrote with HTTP Basic Authentication (https://github.com/tituspijean/flarum-ext-auth-ssowat/issues/17).

**Comment by popindavibe** [comment]
I got in touch with Franz on [discord](https://discordapp.com/channels/360670804914208769/360689644230410251), however after helping to pinpoint the issue, he lost me on the Javascript side of things. 

I am reporting here what has been identified so far:
- PHP code looks good, it authenticates successfully against OpenLDAP, and the username and email attribute are returned, while a Token gets generated.
- at the end of the run, the `make_request` function returns a json array in the form of
```
<script>window.opener.app.authenticationComplete({"username":"test","email":"test@example.com","token":"WzzZ2yvzYn834ftc1BztmACUqGYYpa22ST88kbp0"}); window.close();</script>
```
Problem is, that this piece of Javascript code is not picked up by anyone and just sits there as the response to the POST request.

To prove this would work if picked up by the JS code, entering directly in th borwser console the call `app.authenticationComplete({"username":"test","email":"test@example.com","token":"WzzZ2yvzYn834ftc1BztmACUqGYYpa22ST88kbp0"});` creates the user (if not already in database) and logs you in, as intended when executing the `authenticationComplete` JS function

Franz pointed out the following:
> A simple AJAX call won't suffice. This request is meant to be made in a separate window, opened by JS.
> i.e. you should probably use this component: https://github.com/flarum/core/blob/00bc8fc0bc63643ec850f5d5eec78701225b7f7b/js/src/forum/components/LogInButton.js
> Or replicate this line: https://github.com/flarum/core/blob/00bc8fc0bc63643ec850f5d5eec78701225b7f7b/js/src/forum/components/LogInButton.js#L20

But I can't figure out how to adapt the code, this is far beyond my reach. 
Something else that might help @tituspijean is working code for SSO login available [here](https://github.com/fabwu/flarum-ext-sso/blob/master/js/forum/dist/extension.js), fairly similar to what you have done (more so that github/twitter button extensions).

**Comment by franzliedke** [comment]
I am thinking you should do the `window.open` thing [here](https://github.com/tituspijean/flarum-ext-auth-ldap/blob/845919c8fdbd03aaea876a15acec5be116a93a82/js/forum/src/components/LDAPLogInModal.js#L89).

**Comment by popindavibe** [comment]
@tituspijean did you get some time to look into Franz's info? I tried poking around, but no luck. I just don't understand how all is linked together, between the files, the JS cache and the rest... plus my testing method is manual and tedious, so I'm very much is the dark here.

**Comment by tituspijean** [comment]
Actually not yet! Thanks for reminding me, I was blissfully enjoying having fixed its Yunohost package. :) I will look into it this afternoon.

**Comment by tituspijean** [comment]
Last version (https://github.com/tituspijean/flarum-ext-auth-ldap/releases/tag/v0.6-dev) should fix the issue. Can you confirm on your side?

**Comment by popindavibe** [comment]
I can confirm the user now gets created in the database and subsequent logins are also successful! Thanks a ton for that.

Trying to play one step further, if I use the _displayName_ field from LDAP for user creation (_suggestion_), this prevents me from reconnecting later on.
That said, what would really be nice is to keep using username to log in but showing _displayName_ once logged in. 

I could see a reference to this through online search: https://github.com/flarum/core/commit/eb72307a546cf1bd604dc15b93e699a24a37b2c4 

But if I try adding that field, it doesn't seem to change anything and it still the username that shows on the profile page. As a matter of fact I would have expected the profile page to show both username and displayName fields.  

But again, the issue **is solved**. I think I'll ask Franz regarding the displayName question.

**Comment by tituspijean** [comment]
Great! I will implement it as an option in a future release (i.e. choose between `uid` and `displayName` for Flarum username).
